spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/elifcelik-eva/stock-management-configs.git
          default-label: main
          clone-on-start: true
          force-pull: true
info:
  component: Config Server

server:
  port: 8888

---
spring:
  config:
    activate:
      on-profile: localhost
  cloud:
    config:
      server:
        git:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}

---
spring:
  config:
    activate:
      on-profile: stage
  cloud:
    config:
      server:
        git:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
logging:
  level:
    root: debug
