info:
  component: Product Cache Service
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 5

---
spring:
  config:
    activate:
      on-profile: localhost
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  cloud:
    openfeign:
      client:
        config:
          product-service:
            url: http://localhost:9788

---
spring:
  config:
    activate:
      on-profile: stage
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
  cloud:
    openfeign:
      client:
        config:
          product-service:
            url: http://product-service:9788
